version: "3"
services:
  startup:
    image: hkmaster/docker-demo:latest
    ports:
      - "8083:80"
    # volumes:
    #   - /data/nginx/html:/usr/share/nginx/html
    #   - /data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    #   - /data/nginx/conf.d:/etc/nginx/conf.d
    #   - /data/nginx/logs:/var/log/nginx
    restart: always
    container_name: myNginx2